// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/user/v1/user_profile.proto

package userapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProfileRequest) Reset() {
	*x = QueryProfileRequest{}
	mi := &file_api_user_v1_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProfileRequest) ProtoMessage() {}

func (x *QueryProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProfileRequest.ProtoReflect.Descriptor instead.
func (*QueryProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *QueryProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserProfileDetail   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileReply) Reset() {
	*x = UserProfileReply{}
	mi := &file_api_user_v1_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileReply) ProtoMessage() {}

func (x *UserProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileReply.ProtoReflect.Descriptor instead.
func (*UserProfileReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfileReply) GetItems() []*UserProfileDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserProfileDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileDetail) Reset() {
	*x = UserProfileDetail{}
	mi := &file_api_user_v1_user_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileDetail) ProtoMessage() {}

func (x *UserProfileDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileDetail.ProtoReflect.Descriptor instead.
func (*UserProfileDetail) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfileDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfileDetail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_api_user_v1_user_profile_proto protoreflect.FileDescriptor

const file_api_user_v1_user_profile_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/user/v1/user_profile.proto\x12\auser.v1\"1\n" +
	"\x13QueryProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"D\n" +
	"\x10UserProfileReply\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.user.v1.UserProfileDetailR\x05items\"?\n" +
	"\x11UserProfileDetail\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername2W\n" +
	"\vUserProfile\x12H\n" +
	"\rQueryProfiles\x12\x1c.user.v1.QueryProfileRequest\x1a\x19.user.v1.UserProfileReplyB\x1aZ\x18apps/user/facade/userapib\x06proto3"

var (
	file_api_user_v1_user_profile_proto_rawDescOnce sync.Once
	file_api_user_v1_user_profile_proto_rawDescData []byte
)

func file_api_user_v1_user_profile_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_profile_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_profile_proto_rawDesc), len(file_api_user_v1_user_profile_proto_rawDesc)))
	})
	return file_api_user_v1_user_profile_proto_rawDescData
}

var file_api_user_v1_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_user_v1_user_profile_proto_goTypes = []any{
	(*QueryProfileRequest)(nil), // 0: user.v1.QueryProfileRequest
	(*UserProfileReply)(nil),    // 1: user.v1.UserProfileReply
	(*UserProfileDetail)(nil),   // 2: user.v1.UserProfileDetail
}
var file_api_user_v1_user_profile_proto_depIdxs = []int32{
	2, // 0: user.v1.UserProfileReply.items:type_name -> user.v1.UserProfileDetail
	0, // 1: user.v1.UserProfile.QueryProfiles:input_type -> user.v1.QueryProfileRequest
	1, // 2: user.v1.UserProfile.QueryProfiles:output_type -> user.v1.UserProfileReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_profile_proto_init() }
func file_api_user_v1_user_profile_proto_init() {
	if File_api_user_v1_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_profile_proto_rawDesc), len(file_api_user_v1_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_profile_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_profile_proto_depIdxs,
		MessageInfos:      file_api_user_v1_user_profile_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_profile_proto = out.File
	file_api_user_v1_user_profile_proto_goTypes = nil
	file_api_user_v1_user_profile_proto_depIdxs = nil
}
